spring.datasource.url=jdbc:h2:mem:java-prep;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=USER

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

spring.data.redis.host=redis
spring.data.redis.port=6379
